# Site settings
title: Find Courses - Active Coala
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/course" # the subpath of your site, e.g. /blog/
url: "http://activecoala.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

excerpt_separator: </teaser>

permalink: pretty

sass:
    sass_dir: _resources/sass

collections_dir: _collections

collections:
  courses:
    output: true
  schools:
    output: true
  places:
    output: true
  categories:
    output: true
  agecategories:
    output: true
  subcategories:
    output: true
  levels:
    output: true
  ages:
    output: true
  organizations:
    output: true
  cities:
    output: true

defaults:
 -  scope:
      type: "courses"
    values:
      layout: "course-layout"
 -
    scope:
      type: "schools"
    values:
      layout: "school-layout"
 -
    scope:
      type: "places"
    values:
      layout: "place-layout"
 -
    scope:
      type: "pages"
    values:
      layout: "categories-layout"
      permalink: /categories/:slug
 -
    scope:
        type: "cities"
    values:
      layout: "layout-page-schools"
      permalink: /cities/:slug
 -
    scope:
      type: "levels"
    values:
     layout: "levels-layout"
 -
    scope:
      type: "subcategories"
    values:
     layout: "subcategories-layout"
     permalink: /subcategories/:slug
 -
    scope:
      type: "agecategories"
    values:
     layout: "agecategories-layout"
     permalink: /agecategories/:slug
 -
    scope:
      type: "ages"
    values:
     layout: "age-layout"
     permalink: /ages/age--:slug
 -
    scope:
      type: "organizations"
    values:
     layout: "layout-default"
     permalink: /organization/:slug


# page_gen:
#   - data: 'courses'
#     template: 'airtable/course'
#     name: 'id'
#     dir: 'courses-airtable'


# jekyll_get:
#   - data: places
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Place?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: syllogos
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Organizations?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: schools
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Schools?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: courses
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Courses?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: instructors
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Instructor?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: categories
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Categories?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: subcategories
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Subcategoriess?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: level
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Level?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: age
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Age?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: cities
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Cities?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: agecategories
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Agecategories?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: perioxi
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Perioxi?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: rensponsibles
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Rensponsibles?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: orgcategories
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/Org%20Categories?api_key=keyQVGtEJqpbYYGS0'
#     cache: true
#   - data: federations
#     json: 'https://api.airtable.com/v0/appHI50bSISWqOxUR/federations?api_key=keyQVGtEJqpbYYGS0'
#     cache: true


exclude: ["_gulp-templates",
          "node_modules",
          "_resources",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "yarn.lock"]


include: [
    "_pages"
  ]